<div class="eq-c">
  <span class="radical">
    <span class="n-root">3</span>&radic;
  </span>
  <span class="radicand">81</span>+ln(e<sup>2</sup>) &times;
  <span class="radical">&radic;</span>
  <span class="radicand">121</span> - 5! +
  <span class="intsuma">
    <span class="lim">10</span>
    <span class="sum-frac">&sum;</span>
    <span class="lim"><i>n</i>=0</span>
  </span>
  <span class="fraction">n + </span>
  <span class="intsuma">
    <span class="lim-up">2&pi;</span>
    <span class="sum">&int;</span>
    <span class="lim">0</span>
  </span>
  sin<i>x</i> d<i>x</i>
  + (bin(<code>101001101</code>) &divide; 3) &times; PGCD((1 + 2 + 3 + 4 + 5 - 1)<sup>2</sup>, 2<sup>3</sup> &times; 5<sup>2</sup> &times; 11)
  <p> = ..?</p>

</div>
<div class="">
  <div class="jumbo" id="jumbo">
    <p id="four1"></p>
    <p id="four2"></p>
    <p id="four3"></p>
  </div>
  <a href="../index.php" class="btn btn-primary uTurn">Bref... demi-tour!</a>

</div>
