<div class="container mt-5">
  <div class="card-deck">
    <div class="col-md-4">
      <div class="card">
        <img class="card-img-top p-3" src="img/partager.jpg" alt="Carnet de voyage papier" title="Ecrivez votre histoire"/>
        <div class="card-body">
          <h5 class="card-title">Racontez votre histoire</h5>
          <p class="card-text">Partagez vos moments forts avec vos proches instantanément.</p>
          <a href="#" class="btn btn-primary">Créer un carnet</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <img class="card-img-top p-3" src="img/suivre.jpg" alt="ordinateur" title="Suivez vos proches"/>
        <div class="card-body">
          <h5 class="card-title">Suivez vos proches</h5>
          <p class="card-text">Restez connectés avec vos proches pendant leur voyage.</p>
          <a href="login.php" class="btn btn-primary">S'inscrire</a>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="card">
        <img class="card-img-top p-3" src="img/conserver.jpg" alt="bibliothèque" title="Gardez une trace"/>
        <div class="card-body">
          <h5 class="card-title">Gardez une trace</h5>
          <p class="card-text">Conservez vos souvenirs de voyage à vie.</p>
          <a href="#" class="btn btn-primary">Téléchargement</a>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="trip_list">
  <h2>Vos souvenirs préservés pour tous types de voyage : </h2>
  <div class="trip_icons">
    <div class="description">
      <a href="#">
        <figure>
          <img class="icons" src="img/train.jpg" alt="" title=""/>
          <figcaption>Road trip</figcaption>
        </figure>
      </a>
    </div>
    <div class="description">
      <a href="#">
        <figure>
          <img class="icons" src="img/neige.jpg" alt="" title=""/>
          <figcaption>Week-end</figcaption>
        </figure>
      </a>
    </div>
    <div class="description">
      <a href="#">
        <figure>
          <img class="icons" src="img/bigben.jpg" alt="" title=""/>
          <figcaption>Voyage scolaire</figcaption>
        </figure>
      </a>
    </div>
    <div class="description">
      <a href="#">
        <figure>
          <img class="icons" src="img/tripa2.jpg" alt="" title=""/>
          <figcaption>Escapade</figcaption>
        </figure>
      </a>
    </div>
    <div class="description">
      <a href="#">
        <figure>
          <img class="icons" src="img/romance.jpg" alt="" title=""/>
          <figcaption>Lune de miel</figcaption>
        </figure>
      </a>
    </div>
    <div class="description">
      <a href="#">
        <figure>
          <img class="icons" src="img/worldtour.jpg" alt="" title=""/>
          <figcaption>Découverte</figcaption>
        </figure>
      </a>
    </div>
  </div>
</div>
<div class="container presentation">
  <div class="row alignement">
    <div class="col-md-3 alignement_height">
      <form class="choice" action="index.html" method="POST">
        <label for="depart" class="depart">Départ le : </label>
        <input type="date" value="<?=$departure;?>" id="depart" class="depart"/>
        <a href="#" class="btn btn-primary depart">C'est parti !</a>
      </form>
    </div>
    <div class="col-md-9">
      <ul class="">
        <li><span>Racontez vos histoires</span> : que ce soit pour un <strong>week-end au ski, une escapade du quotidien, votre lune de miel, un road-trip entre amis, un tour du Monde en sac à dos ou un séjour à la rencontre d'une autre culture</strong>. Vous pourrez décrire vos expériences, connaître précisément la position des photos que vous aurez prises, prendre des notes comme vous le feriez avecun carnet de voyage... mais en beaucoup plus ludique !</li>
        <li><span>Gardez le contact avec vos proches</span> : rendez vos amis ou votre famille envieux de vous rejoindre lors de vos pérégrinations ! Plutôt que partager vos photos avec le monde entier, vos carnets de voyage ne sont visibles que par vos <em>followers</em>. <strong>Décrivez vos sensations librement</strong> sans peur d'être jugé, <strong>faites ressentir vos émotions</strong> au moment même où vous les vivez. Dès que vous récupérez une connexion Wi-Fi, vos carnets sont automatiquement synchronisés!</li>
        <li><span>Conservez une trace de vos découvertes</span> : à la fin de votre escapade, vous avez la possibilité de <strong>télécharger gratuitement le PDF de votre séjour</strong>. Mieux encore ! Vous pouvez sélectionner les photos et les commentaires que vous souhaitez voir apparaître !</li>
      </ul>
      <p>Alors foncez ! L'inscription, l'utilisation et l'impression... <strong>tout est gratuit !</strong> Le monde n'attend que vous pour être découvert !</p>
    </div>
  </div>
</div>
</main>
<footer class="footer">
  <div class="legal">
    <ul>
      <li><a class="footer_link" href="#">Plan du site</a></li>
      <li><a class="footer_link" href="#">FAQ</a></li>
      <li><a class="footer_link" href="#">Comment ça marche ?</a></li>
      <li><a class="footer_link" href="mailto:">Contact</a></li>
      <li><a class="footer_link" href="admin/index.php">Entrée des artistes</a></li>
    </ul>
  </div>
  <div class="copyright">
    <p><i class="fa fa-copyright" aria-hidden="true"></i> 2018 &lt;/&gt; <span style="text-decoration:underline;">mr-p.fr</span> &lt;/&gt; </p>
  </div>


</footer>
