<div class="content">
  <table class="table index">
    <thead>
      <tr>
        <th scope="col">Avatar</th>
        <th scope="col">Pseudo</th>
        <th scope="col">Prénom</th>
        <th scope="col">Nom</th>
        <th scope="col">Age</th>
        <th scope="col">E-mail</th>
        <th scope="col">Bio</th>
        <th scope="col">Pays</th>
        <th scope="col">Membre depuis le</th>
        <th scope="col">Niveau</th>
        <th scope="col">Gérer</th>
      </tr>
    </thead>
    <tbody>
      <?php foreach ($dbResult as $key => $value):?>
      <tr class="list">
        <td><img src="<?=$value['avatar'];?>" alt="avatar de <?=$value['pseudo'];?>"/></td>
        <td><?=$value['pseudo'];?></td>
        <td><?=$value['firstName'];?></td>
        <td><?=$value['lastName'];?></td>
        <td><?=age($value['dateToCompute']);?> ans</td>
        <td><?=$value['email'];?></td>
        <td><?=$value['bio'];?></td>
        <td><?=$value['nom_fr_fr'];?></td>
        <td><?=$value['registerDate'];?></td>
        <td><?=$value['levelName'];?></td>
        <td><a href="editUser.php?line=<?=$value['idTripper'];?>"><i class="fa fa-pencil-square-o"></i></a> <a data-id="<?=$value['idTripper'];?>" class="lienModal" href="delUser.php?line=<?=$value['idTripper'];?>"><i class="fa fa-user-times"></i></a></td>
      </tr>
      <?php endforeach;?>
    </tbody>
  </table>

  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="centeredModal" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="Confirmation">Confirmation</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <p>Êtes-vous sûr de vouloir supprimer cet utilisateur ?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="col btn btn-secondary" data-dismiss="modal">Annuler</button>
          <a href="#" class="col btn btn-primary" id="deleteLink">Confirmer</a>
        </div>
      </div>
    </div>
  </div>

</div>
