<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="<?=$path;?>/public/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <link href="<?=$path;?>/public/css/jquery-ui.min.css" rel="stylesheet" type="text/css" />
  <link href="<?=$path;?>/public/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="<?=$path;?>/public/css/main.css">
  <title>TripNoteBook | <?=$title;?></title>
</head>
<body>
  <header>
    <nav class="navbar navbar-expand-lg navbar-light">
      <ul class="navbar-nav">
        <li class="nav-item"><a href="index.php" class="nav-link active" style="color:#FFF;">Retour à l'accueil</a></li>
        <li class="nav-item"><a href="../logout.php" class="nav-link <?=(isset($_SESSION['logged']) && $_SESSION['logged'] === true)?'show_success':'hidden';?>" style="color:#FFF;">Déconnexion <i class="fa fa-sign-out"></i></a></li>
      </ul>
      <!-- <h1 class="navbar-brand" href="#"><?=$title;?></h1> -->
      <!-- <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup"> -->
        <!-- <ul class="navbar-nav">
          <li class="nav-item"><a href="index.php" class="nav-link <?=(isset($_SESSION['logged']) && $title == 'Accueil Admin')?'active':'';?>">Accueil</a></li>
          <li class="nav-item"><a href="addUser.php" class="nav-link <?=(isset($_SESSION['logged']) && $title == 'Ajouter un utilisateur')?'active':'';?>">Ajouter un utilisateur</a></li>
          <li class="nav-item"><a href="#" class="nav-link <?=(isset($_SESSION['logged']) && $title == 'Rédiger un article')?'active':'';?>">Rédiger un article</a></li>
          <li class="nav-item"><a href="logout.php" class="nav-link <?=(isset($_SESSION['logged']))?'active':'disabled';?>">Déconnexion <i class="fa fa-sign-out"></i></a></li>
        </ul>
        <div class="d-flex justify-content-end">
          <span class="message"><?=(isset($_SESSION['logged']))?'Bienvenue '.$_SESSION['user'].' !':'';?></span>
        </div>
      </nav> -->


  </header>
    <h1><?=$title;?></h1>



<main>
  <?php include($vue);?>
</main>


  <script src="<?=$path;?>/public/js/jquery.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/jquery-ui.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/popper.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/bootstrap.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="<?=$path;?>/public/js/main.js"></script>
</body>
</html>
