<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="<?=$path;?>/public/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <link href="<?=$path;?>/public/css/jquery-ui.min.css" rel="stylesheet" type="text/css" />
  <link href="<?=$path;?>/public/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="<?=$path;?>/public/css/main.css">
  <title>TripNoteBook | <?=$title;?></title>
</head>
<body>

<header <?=(isset($index) && $index)?'':'style="position: static'?>">
  <?php if (isset($index) && $index) :?>
  <img src="img/accueil.jpg" alt="image d'accueil" title="banner" width="100%"/>
  <?php endif;?>
  <nav class="grid">
    <figure class="g">
      <img class="logo" src="img/logo.jpg" alt="logo" title="écrivez votre histoire"/>
    </figure>
    <div class="nav-item a"><a href="index.php" class="nav-link">Accueil</a></div>
    <div class="nav-item b"><a href="#" class="nav-link">Parcourir les carnets</a></div>
    <div class="nav-item c"><a href="#" class="nav-link">Comment ça marche ?</a></div>
    <div class="nav-item d"><a href="#" class="nav-link">Livre d'or</a></div>

    <?php if (isset($index) && $index) :?>
    <div class="nav-item f"><a href="login.php" class="nav-link">Connexion</a></div>
    <div class="nav-item e"><a href="login.php" class="nav-link">Inscription</a></div>
    <?php endif;?>

    <?php if (!empty($_SESSION) && $_SESSION['logged']) :?>
    <div class="nav-item h myAccount">

      <div class="">
        <a href="#" class="nav-item">
          <img src="<?=str_replace('../','./',$_SESSION['avatar']);?>" alt="Avatar de <?=$_SESSION['pseudo'];?>" style="border-radius:50%;border: 1px solid #000;"/>
        </a>
      </div>
      <div class="twoLinesMenu">
        <p class="nav-link">
          Bienvenue <?=$_SESSION['pseudo'];?> !
        </p>
        <p class="nav-link">
          <a href="#" id="myAccount">Mon espace privé</a>
        </p>
        <div class="toggleMenu showMenu" id="toggleMenu">
          <ul id="displayMenu">
            <li><a href="./CRUD/editTripper.php">Editer mon profil <i class="fa fa-pencil" aria-hidden="true"></i></a></li>
            <li><a href="#">Voir mes carnets <i class="fa fa-eye" aria-hidden="true"></i></a></li>
            <li class="logoutLink"><a href="logout.php">Déconnexion <i class="fa fa-sign-out"></i></a></li>
          </ul>
        </div>
      </div>

    </div>
    <?php endif;?>

  </nav>
  <?php if (isset($index) && $index) :?>

  <div class="title_group">
    <h1>Racontez ce que vous vivez</h1>
    <div class="link_buttons">
      <a href="login.php" class="btn">Inscription</a>
      <a href="#" class="btn">Démarrer</a>
    </div>
  </div>
  <?php endif;?>
</header>

<main <?=(!isset($index) || !$index)?'style="position: static;"':'';?>>
  <div class="container" style="margin-top: 5rem;">
    <?php include($vue);?>
  </div>
</main>


  <script src="<?=$path;?>/public/js/jquery.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/jquery-ui.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/popper.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/bootstrap.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="<?=$path;?>/public/js/main.js"></script>
</body>
</html>
