<!DOCTYPE html>
<html lang="fr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link href="<?=$path;?>/public/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
  <link href="<?=$path;?>/public/css/jquery-ui.min.css" rel="stylesheet" type="text/css" />
  <link href="<?=$path;?>/public/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
  <link rel="stylesheet" href="<?=$path;?>/public/css/main.css">
  <title>TripNoteBook | <?=$title;?></title>
</head>
<body>

<header <?=(isset($index) && $index)?'style="height:100vh"':'style="position: static"'?>>
  <?php if (isset($index) && $index) :?>
  <div class="accueil"></div>
  <?php endif;?>
  <nav class="grid">
    <div class="volet" id="voletFerme">
      <div class="volet" id="volet">
          <a href="#volet" class="burger" id="retour"><i class="fa fa-times" aria-hidden="true"></i></a>
          <a href="#voletFerme" class="burger" id="aller"><i class="fa fa-bars" aria-hidden="true"></i></a>
        <div class="fourFirst" id="fourFirst">
          <div class="nav-item a">
            <a href="<?=$path . '/';?>index.php" class="nav-link">Accueil</a>
          </div>
          <div class="nav-item b">
            <a href="#" class="nav-link">Parcourir les carnets</a>
          </div>
          <div class="nav-item c">
            <a href="#" class="nav-link">Comment ça marche ?</a>
          </div>
          <div class="nav-item d">
            <a href="#" class="nav-link">Livre d'or</a>
          </div>
        </div>
      </div>
    </div>

    <?php if ((isset($index) && $index) && (empty($_SESSION))) :?>
      <div class="twoLast">
        <div class="nav-item f"><a href="login.php" class="nav-link">Connexion</a></div>
        <div class="nav-item e"><a href="login.php" class="nav-link">Inscription</a></div>
      </div>
    <?php endif;?>

    <?php if (!empty($_SESSION) && $_SESSION['logged']) :?>
    <div class="nav-item h myAccount">

      <div class="">
        <a href="#" class="nav-item">
          <img src="<?=str_replace('../',$path.'/',$_SESSION['avatar']);?>" alt="Avatar de <?=$_SESSION['pseudo'];?>" style="border-radius:50%;border: 1px solid #000;"/>
        </a>
      </div>
      <div class="twoLinesMenu">
        <p class="nav-link">
          Bienvenue <?=$_SESSION['pseudo'];?> !
        </p>
        <p class="nav-link">
          <a href="#" id="myAccount">Mon espace privé</a>
        </p>
        <div class="toggleMenu showMenu" id="toggleMenu">
          <ul id="displayMenu">
            <li><a href="./CRUD/editTripper.php">Editer mon profil <i class="fa fa-pencil" aria-hidden="true"></i></a></li>
            <li><a href="#">Voir mes carnets <i class="fa fa-eye" aria-hidden="true"></i></a></li>
            <li class="logoutLink"><a href="<?=$path . '/';?>logout.php" onclick="localStorage.clear();">Déconnexion <i class="fa fa-sign-out"></i></a></li>
          </ul>
        </div>
      </div>

    </div>
    <?php endif;?>

  </nav>
  <?php if (isset($index) && $index) :?>

  <div class="title_group">
    <h1>Racontez ce que vous vivez</h1>
    <div class="link_buttons" id="link_buttons">
      <a href="login.php" class="headerButton">Inscription</a>
      <a href="#" class="headerButton">Démarrer</a>
    </div>
  </div>
  <?php endif;?>
</header>

<main <?=(!isset($index) || !$index)?'style="position: relative;margin-top:80px"':'';?>>
  <div class="container" style="margin-top: 5rem;">
    <?php include($vue);?>
  </div>
</main>


  <script src="<?=$path;?>/public/js/jquery.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/jquery-ui.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/popper.min.js" type="text/javascript"></script>
  <script src="<?=$path;?>/public/js/bootstrap.min.js" type="text/javascript"></script>
  <script type="text/javascript" src="<?=$path;?>/public/js/sha256.js"></script>
  <script type="text/javascript" src="<?=$path;?>/public/js/main.js"></script>
</body>
</html>
