
  <div class="row">
    <div class="col-md-6">
      <form class="form-signin" action="./formTripper.php" method="GET">
          <h2 class="h3 mb-3 font-weight-normal">Pas encore de compte ?</h2>
          <input type="text" id="inputPseudo" class="form-control" placeholder="Pseudo" name="inputPseudo" required autofocus>
          <input type="email" id="inputEmail" class="form-control" placeholder="E-mail" name="inputEmail" required>
          <button class="btn btn-lg btn-primary btn-block" type="submit" id="register">Je m'inscris !</button>
        </form>
    </div>
    <div class="col-md-6">
      <form class="form-signin" action="login.php" method="POST">
          <h2 class="h3 mb-3 font-weight-normal">J'ai déjà un compte !</h2>
          <input type="text" id="userNameAuth" class="form-control" placeholder="Pseudo" name="userNameAuth" value="<?=$checkUser;?>" required autofocus>
          <input type="password" id="inputPassword" class="form-control" placeholder="Mot de passe" name="inputPassword" value="<?=$checkPwd;?>" required>
          <button class="btn btn-lg btn-primary btn-block" type="submit" id="connecter">Je me connecte !</button>
          <p class="mt-5 mb-3 errorMessage"><?=(!empty($errorMessage))?$errorMessage[0]:'';?></p>
        </form>
    </div>
  </div>
